module.exports = {
    singleQuote: true,
    trailingComma: 'all',
    tabWidth: 4,
    semi: true,
    arrowParens: 'always',
    bracketSameLine: true,
    bracketSpacing: true,
    experimentalTernaries: false,
    jsxSingleQuote: false,
    quoteProps: 'as-needed',
    singleAttributePerLine: true,
    htmlWhitespaceSensitivity: 'css',
    vueIndentScriptAndStyle: false,
    proseWrap: 'preserve',
    insertPragma: false,
    printWidth: 100,
    requirePragma: false,
    useTabs: false,
    importOrder: [
        '^node:.*$',
        '',
        '<THIRD_PARTY_MODULES>',
        '',
        '^@/src/commands',
        '^@/src/logger',
        '^@/src/utils',
        '',
        '^[./]',
    ],
    plugins: ['@ianvs/prettier-plugin-sort-imports'],
};
